#! /bin/sh

# This is a shell script that load and unload device drivers

case "$1" in
    # If the script is called with the "start", load the drivers
    start)
        #  drivers are loading
        echo "loading drivers"

        # Execute the driver load scripts
        scull_load
        module_load hello
        module_load faulty
        ;;

    # If the script is called with the "stop" argument, stop the daemon.
    stop)
        # Print a message indicating that the drivers are unloading
        echo "Unloading drivers"

        # Execute the driver unload scripts
        module_unload faulty
        module_unload hello
        scull_unload
        ;;
    # If the script is called with any other argument, print usage information.
    *)
        # Print a message explaining the correct usage of the script.
        echo "Usage:  $0 {start|stop}"

    # Exit the script with an error code of 1 to indicate that it was used incorrectly.
    exit 1
esac

# Exit the script with a success code of 0.
exit 0
